apiVersion: v1
kind: Pod
metadata:
  name: file-config-container
spec:
  containers:
    - name: file-config-container
      image: busybox:1.24
      command: [ "/bin/cat", "/etc/config/this.is.great" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: lit-config
  restartPolicy: Never
