apiVersion: v1
kind: Pod
metadata:
  name: secret-file-pod 
spec:
  containers:
    - name: secret-file-pod 
      image: busybox:1.24
      command: [ "/bin/cat", "/etc/my-secret/username" ]
      volumeMounts:
        - name: foo
          mountPath: /etc/my-secret
          readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: my-secret
  restartPolicy: Never
